#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Rune Hammersland"
email = "273190+yaunj@users.noreply.github.com"
username = "yaunj"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
# Rebase all branches onto the new trunk(), as long as they're mutable
restack = ["rebase", "--onto", "trunk()", "--source", "roots(trunk()..) & mutable()", "--simplify-parents"]
# Inserts the given revset as a new branch under the megamerge
stack = ["rebase", "--after", "trunk()", "--before", "closest_merge(@)", "--revision"]
# Insert the current changes as a new branch under the megamerge
stage = ["stack", "closest_merge(@)+:: ~ empty()"]

[colors]
"diff token" = { underline = false}  # remove underlines in diffs

[fix.tools.gofmt]
patterns = ["glob:'**/*.go'"]
command = ["gofmt"]

[fix.tools.ruff]
command = ["ruff", "-", "--stdin-filename=$path"]
patterns = ["glob:'**/*.py'"]

[fix.tools.terraform]
command = ["terraform", "fmt", "-"]
patterns = ["glob:'**/*.tf'"]

[revsets]

[revset-aliases]
#"trunk()" = "coalesce(present(main@origin), present(master@origin))"
"closest_merge(to)" = "heads(::to & merges())"
current = 'trunk()::@'

[ui]
default-command = "log"
